"""Writes bot/known_maps.py: the ladder's own maps (maps/ladder/*.map, recovered from ladder replays by
tools/replay_maps.py) in the Brain's terms, so a dragon that recognises its map can know every portal pair, every
kelp edge and every pearl-spawning tile from its first turn (bot/brain.py DEFAULTS "map_oracle").

    .venv\\Scripts\\python.exe tools\\gen_known_maps.py [--check]

--check only verifies that bot/known_maps.py matches the maps (exit 1 if it is stale).
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from mapfile import WEST, GameMap  # noqa: E402

OUT = ROOT / "bot" / "known_maps.py"
HEADER = '''"""Generated by tools/gen_known_maps.py from maps/ladder/*.map -- do not edit by hand.

MAPS[(width, height)] = ((name, kh, kv, ph, pv, pairs, spawns), ...). kh/kv/ph/pv/spawns are bitboards in the Brain's
cell order (y * width + x): a kh/kv bit is kelp on that tile's north/west edge, ph/pv a portal, spawns the tiles that
ever spawn a pearl. pairs holds the portal pairs as (edge key, edge key), an edge key being cell * 2 + (1 for the west
edge, 0 for the north edge).
"""
MAPS = {
'''


def entry(m):
    kh = kv = ph = pv = spawns = 0
    for (x, y, d) in m.kelp:
        if d == WEST:
            kv |= 1 << (y * m.w + x)
        else:
            kh |= 1 << (y * m.w + x)
    ends = {}
    for (x, y, d), pid in m.portals.items():
        if d == WEST:
            pv |= 1 << (y * m.w + x)
        else:
            ph |= 1 << (y * m.w + x)
        ends.setdefault(pid, []).append((y * m.w + x) * 2 + (1 if d == WEST else 0))
    pairs = tuple(sorted(tuple(sorted(e)) for e in ends.values() if len(e) == 2))
    for (x, y), (lo, hi) in m.tiles.items():
        if hi > 0:
            spawns |= 1 << (y * m.w + x)
    return kh, kv, ph, pv, pairs, spawns


def render():
    by_size = {}
    for p in sorted((ROOT / "maps" / "ladder").glob("*.map")):
        m = GameMap.loads(p.read_text())
        by_size.setdefault((m.w, m.h), []).append((p.stem, *entry(m)))
    out = [HEADER]
    for size in sorted(by_size):
        out.append(f"    {size}: (\n")
        for name, kh, kv, ph, pv, pairs, spawns in by_size[size]:
            out.append(f"        ({name!r}, {kh:#x}, {kv:#x}, {ph:#x}, {pv:#x}, {pairs!r}, {spawns:#x}),\n")
        out.append("    ),\n")
    out.append("}\n")
    return "".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        if OUT.read_text() != text:
            print(f"{OUT} is stale: rerun tools/gen_known_maps.py")
            raise SystemExit(1)
        print("ok  bot/known_maps.py matches maps/ladder")
        return
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
